"""empty message

Revision ID: e975322795b6
Revises: 
Create Date: 2023-05-01 23:58:17.251997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e975322795b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credentials', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('photo_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('placement',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('schedule_schema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('to_be_active_from', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', name='staff_role'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('placement', sa.String(), nullable=True),
    sa.Column('instructor', sa.Integer(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('place_limit', sa.Integer(), nullable=True),
    sa.Column('registration_opens', sa.Integer(), nullable=True),
    sa.Column('available_registration', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['instructor'], ['instructor.id'], ),
    sa.ForeignKeyConstraint(['placement'], ['placement.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booked_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client', sa.Integer(), nullable=False),
    sa.Column('program', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client', 'program', 'date', name='one_booking_per_client_uc')
    )
    op.create_table('schema_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('day_time', sa.Time(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('program', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program'], ['program.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_schema_record',
    sa.Column('schedule_schema', sa.Integer(), nullable=False),
    sa.Column('schema_record', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_schema'], ['schedule_schema.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schema_record'], ['schema_record.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_schema', 'schema_record')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_schema_record')
    op.drop_table('schema_record')
    op.drop_table('booked_classes')
    op.drop_table('program')
    op.drop_table('staff')
    op.drop_table('schedule_schema')
    op.drop_table('placement')
    op.drop_table('instructor')
    op.drop_table('client')
    op.drop_table('category')
    # ### end Alembic commands ###
