- name: Refresh apt cache
  apt: update_cache=yes cache_valid_time=86400

- name: Install requirements
  apt:
    pkg:
      - build-essential
      - git
      - libffi-dev
      - libssl-dev
      - python3
      - python3-apt
      - python3-distutils
      - python3-pip
      - python3-setuptools
      - python3-virtualenv

- name: Install NodeJS from snap
  community.general.snap:
    classic: true
    name: node

- name: Install angular/cli
  community.general.npm:
    global: true
    name: "@angular/cli"

- name: Install angular dependencies
  community.general.npm:
    path: "{{ app_root_dir }}/sport-app-client/"

