from .programs.category import CategoryService
from .programs.program import ProgramService
from .programs.instructor import InstructorService
from .programs.placement import PlacementService
from .schedules.schedule import ScheduleService
from .schedules.records import RecordService
from .schedules.schema import SchemaService
from .client import ClientService
from .auth import AuthService