- name: Create config directory
  file: path="{{ app_root_dir }}/nginx" state=directory

- name: Create conf.d directory
  file: path="{{ app_root_dir }}/nginx/conf.d" state=directory

- name: Render nginx config
  template: src=nginx.conf.j2 dest="{{ app_root_dir }}/nginx/nginx.conf"

- name: Modify permissions of /etc/letsencrypt/archive
  file:
    path: /etc/letsencrypt/archive
    mode: '777'

- name: Modify permissions of /etc/letsencrypt/live
  file:
    path: /etc/letsencrypt/live
    mode: '777'
